[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pyth_oracle_1 = "5hC6mtKFiK6YBZq2PMdju5rP2qGuuHsXnNS7Neqhtays"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=bdb45793-138e-4ff8-b8f4-cd7dba5545df"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx --test --test-reporter=spec tests/*.ts"
